// Generated by dts-bundle-generator v9.5.1

export interface TestPlugin {
	/**
	 * The unique name of the plugin
	 */
	name: string;
	/**
	 * Brief description of the plugin
	 */
	description: string;
	/**
	 * Function to be executed on plugin execution
	 */
	execute(): void;
}
declare const plugins: TestPlugin[];
declare function executePlugins(excluded?: string[]): void;

declare namespace plugins$1 {
	export { TestPlugin, executePlugins, plugins };
}

export {
	plugins$1 as plugins,
};

export {};
